### ISSUE TITLE
how to uninstall completely for reinstall

### ISSUE THREAD

**Issue by williamcorney** [mshibanami/redirect-web#28] opened 2024-04-26 22:05 UTC
How can I completely remove to reinstall?  what locations are written to?

I have tried uninstalling /reinstalling but suspect there are some corrupt files somewhere causing the problem

![image](https://github.com/mshibanami/redirect-web/assets/118494245/a5eb3be6-0220-4adb-9a21-de58e8dba956)

the page loads ok if I run from applications but if I try to launch the screen in safari I get this half loaded look

**Comment by mshibanami** [comment] 2024-04-27 02:22
Hi @williamcorney, sorry for any inconvenience.
To completely uninstall the extension, please try these:

1. Disable the extension on Safari
    1. Open Safari
    2. Go to the menu bar > "Safari" > Settings > Extensions tab
    3. Uncheck "Redirect Web for Safari"
2. Remove the "Redirect Web for Safari" app
    1. Open the Applications folder
    2. Find the Redirect Web for Safari app and delete it
3. Delete setting files
    1. Open `/Users/manabu/Library/Containers`
    2. Delete `Redirect Web for Safari` folders
4. Restart the macOS

---

This kind of UI issue is generally caused by Safari or macOS, and it may be solved by restarting the macOS. If you are still interested in this extension, I recommend you try it.

**Comment by mshibanami** [comment] 2024-04-27 02:25
Hi @williamcorney, sorry for any inconvenience.
To completely uninstall the extension, please try these:

1. Disable the extension on Safari
    1. Open Safari
    2. Go to the menu bar > "Safari" > Settings > Extensions tab
    3. Uncheck "Redirect Web for Safari"
2. Remove the "Redirect Web for Safari" app
    1. Open the Applications folder
    2. Find the Redirect Web for Safari app and delete it
3. Delete setting files
    1. Open `~/Library/Containers`
    2. Delete `Redirect Web for Safari` folders
4. Restart the macOS

---

By the way, this kind of UI issue is generally caused by Safari or macOS, and it may be solved by just restarting the macOS. So, I recommend you try it before uninstalling it.

**Comment by mshibanami** [comment] 2024-05-01 04:03
I'm closing this issue, but please feel free to reopen it if the problem persists.

**Closed by mshibanami** 2024-05-01 04:03 UTC
